WITH TICKET AS (SELECT
    *
FROM
(
SELECT
    MARCA,
    MES,
    SUM(TOTAL)/COUNT(NUNOTA) AS TOTAL
FROM
(
SELECT
   TGFCAB.NUNOTA,
   trim(TGFPRO.MARCA) AS MARCA,
   TIM_MONTH(TGFCAB.DTENTSAI) AS MES,
   ROUND(SUM( ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI)  * VCA.INDITENSBRUTO) * CASE WHEN TGFTOP.BONIFICACAO = 'S' THEN 0 ELSE 1 END * TGFTOP.GOLDEV ),2) AS TOTAL
FROM TGFCAB
  , TGFITE ITE
  , VGFCAB VCA
  , TGFPRO
  , TGFTOP
  , TSICID CID JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE TGFCAB.STATUSNOTA = 'L'
  AND TGFCAB.NUNOTA = ITE.NUNOTA
  AND TGFCAB.NUNOTA = VCA.NUNOTA
  AND CID.CODCID = (SELECT PAR.CODCID FROM TGFPAR PAR WHERE PAR.CODPARC = TGFCAB.CODPARC)
  AND UFS.UF = 'MG'
  AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
  AND ITE.SEQUENCIA > 0
  AND ITE.CODPROD = TGFPRO.CODPROD
--  AND TGFPRO.CODPROD = 102120
  AND TGFCAB.CODVEND = 45
  AND TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
  AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
  AND TGFTOP.GOLSINAL = -1
  --AND TGFPRO.MARCA IN ('ESAB')
    AND TRUNC(TGFCAB.DTENTSAI) >= '01/01/2022' AND TRUNC(TGFCAB.DTENTSAI) <= '31/12/2022'
    AND ((TGFCAB.TIPMOV in ('V','D') AND 
    TGFCAB.CODEMP in (1,2,3,5) AND 
    TGFCAB.STATUSNOTA = 'L'))  AND TGFCAB.NUNOTA = ITE.NUNOTA  AND (TGFCAB.CODEMP IN (5, 2, 3, 1)) AND ITE.CODPROD = TGFPRO.CODPROD  /*AND (TGFPRO.MARCA IN ('3M', 'MARLUVAS'))*/ 
GROUP BY trim(TGFPRO.MARCA), TGFCAB.DTENTSAI, TGFCAB.NUNOTA) GROUP BY MARCA, MES)
PIVOT
    (SUM(TOTAL) FOR MES IN (1 AS JANEIRO2, 2 AS FEVEREIRO2, 3 AS MARÇO2, 4 AS ABRIL2, 5 AS MAIO2, 6 AS JUNHO2, 7 AS JULHO2, 8 AS AGOSTO2, 9 AS SETEMBRO2, 10 AS OUTUBRO2, 11 AS NOVEMBRO2, 12 AS DEZEMBRO2))
),
FATUR AS (SELECT
    *
FROM
(
SELECT
   trim(TGFPRO.MARCA) AS MARCA,
   TIM_MONTH(TGFCAB.DTENTSAI) AS MES,
   ROUND(SUM( ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI)  * VCA.INDITENSBRUTO) * CASE WHEN TGFTOP.BONIFICACAO = 'S' THEN 0 ELSE 1 END * TGFTOP.GOLDEV ),2) AS TOTAL
FROM TGFCAB
  , TGFITE ITE
  , VGFCAB VCA
  , TGFPRO
  , TGFTOP
  , TSICID CID JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE TGFCAB.STATUSNOTA = 'L'
  AND TGFCAB.NUNOTA = ITE.NUNOTA
  AND TGFCAB.NUNOTA = VCA.NUNOTA
  AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
  AND ITE.SEQUENCIA > 0
  AND ITE.CODPROD = TGFPRO.CODPROD
  AND TGFCAB.CODVEND = 45
  AND CID.CODCID = (SELECT PAR.CODCID FROM TGFPAR PAR WHERE PAR.CODPARC = TGFCAB.CODPARC)
  AND UFS.UF = 'MG'
--  AND TGFPRO.CODPROD = 102120
  AND TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
  AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
  AND TGFTOP.GOLSINAL = -1
  --AND TGFPRO.MARCA IN ('ESAB')
    AND TRUNC(TGFCAB.DTENTSAI) >= '01/01/2022' AND TRUNC(TGFCAB.DTENTSAI) <= '01/04/2022'
    AND ((TGFCAB.TIPMOV in ('V','D') AND 
    TGFCAB.CODEMP in (1,2,3,5) AND 
    TGFCAB.STATUSNOTA = 'L'))  AND TGFCAB.NUNOTA = ITE.NUNOTA  AND (TGFCAB.CODEMP IN (5, 2, 3, 1)) AND ITE.CODPROD = TGFPRO.CODPROD  /*AND (TGFPRO.MARCA IN ('3M', 'MARLUVAS'))*/ GROUP BY trim(TGFPRO.MARCA), TGFCAB.DTENTSAI
)
PIVOT
    (SUM(TOTAL) FOR MES IN (1 AS JANEIRO, 2 AS FEVEREIRO, 3 AS MARÇO, 4 AS ABRIL, 5 AS MAIO, 6 AS JUNHO, 7 AS JULHO, 8 AS AGOSTO, 9 AS SETEMBRO, 10 AS OUTUBRO, 11 AS NOVEMBRO, 12 AS DEZEMBRO))
)

SELECT
    T.MARCA,
    CASE WHEN SNK_FORMAT_MOEDA(F.JANEIRO)||' ('||SNK_FORMAT_MOEDA(T.JANEIRO2)||')' = ' ()' THEN '0' ELSE SNK_FORMAT_MOEDA(F.JANEIRO)||' ('||SNK_FORMAT_MOEDA(T.JANEIRO2)||')' END AS JANEIRO,
    CASE WHEN SNK_FORMAT_MOEDA(F.FEVEREIRO)||' ('||SNK_FORMAT_MOEDA(T.FEVEREIRO2)||')' = ' ()' THEN '0' ELSE SNK_FORMAT_MOEDA(F.FEVEREIRO)||' ('||SNK_FORMAT_MOEDA(T.FEVEREIRO2)||')' END  AS FEVEREIRO,
    CASE WHEN SNK_FORMAT_MOEDA(F.MARÇO)||' ('||SNK_FORMAT_MOEDA(T.MARÇO2)||')' = ' ()' THEN '0' ELSE SNK_FORMAT_MOEDA(F.MARÇO)||' ('||SNK_FORMAT_MOEDA(T.MARÇO2)||')' END AS MARÇO,
    F.ABRIL||' ('||T.ABRIL2||')' AS ABRIL,
    CASE WHEN F.MAIO||' ('||T.MAIO2||')' = ' ()' THEN '0' ELSE F.MAIO||' ('||T.MAIO2||')' END AS MAIO
FROM
    TICKET T JOIN FATUR F ON T.MARCA = F.MARCA 
    -------------------------------------------------------------------



    SELECT
    *
FROM
(
SELECT
    MARCA,
    MES,
    SUM(TOTAL)/COUNT(NUNOTA) AS TOTAL
FROM
(
SELECT
   TGFCAB.NUNOTA,
   trim(TGFPRO.MARCA) AS MARCA,
   TIM_MONTH(TGFCAB.DTENTSAI) AS MES,
   ROUND(SUM( ((ITE.VLRTOT - ITE.VLRDESC - NVL(ITE.VLRREPRED,0) + ITE.VLRSUBST + ITE.VLRIPI)  * VCA.INDITENSBRUTO)
   * CASE WHEN TGFTOP.BONIFICACAO = 'S' THEN 0 ELSE 1 END * TGFTOP.GOLDEV ),2) AS TOTAL
FROM TGFCAB
  , TGFITE ITE
  , VGFCAB VCA
  , TGFPRO
  , TGFTOP
  , TSICID CID JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE TGFCAB.STATUSNOTA = 'L'
  AND TGFCAB.NUNOTA = ITE.NUNOTA
  AND TGFCAB.NUNOTA = VCA.NUNOTA
  AND CID.CODCID = (SELECT PAR.CODCID FROM TGFPAR PAR WHERE PAR.CODPARC = TGFCAB.CODPARC)
  AND UFS.UF = 'MG'
  AND (NOT EXISTS(SELECT 1 FROM TGFVAR VAR WHERE VAR.NUNOTA = ITE.NUNOTA AND VAR.NUNOTAORIG = VAR.NUNOTA AND VAR.SEQUENCIAORIG = ITE.SEQUENCIA))
  AND ITE.SEQUENCIA > 0
  AND ITE.CODPROD = TGFPRO.CODPROD
--AND TGFPRO.CODPROD = 102120
  AND TGFCAB.CODVEND = 45
  AND TGFCAB.CODTIPOPER = TGFTOP.CODTIPOPER
  AND TGFCAB.DHTIPOPER = TGFTOP.DHALTER
  AND TGFTOP.GOLSINAL = -1
  --AND TGFPRO.MARCA IN ('ESAB')
    AND TRUNC(TGFCAB.DTENTSAI) >= '01/01/2022' AND TRUNC(TGFCAB.DTENTSAI) <= '31/12/2022'
    AND ((TGFCAB.TIPMOV in ('V','D') AND 
    TGFCAB.CODEMP in (1,2,3,5) AND 
    TGFCAB.STATUSNOTA = 'L'))  AND TGFCAB.NUNOTA = ITE.NUNOTA  AND (TGFCAB.CODEMP IN (5, 2, 3, 1)) AND ITE.CODPROD = TGFPRO.CODPROD  /*AND (TGFPRO.MARCA IN ('3M', 'MARLUVAS'))*/ 
GROUP BY trim(TGFPRO.MARCA), TGFCAB.DTENTSAI, TGFCAB.NUNOTA) GROUP BY MARCA, MES)
PIVOT
    (SUM(TOTAL) FOR MES IN (1 AS JANEIRO2, 2 AS FEVEREIRO2, 3 AS MARÇO2, 4 AS ABRIL2, 5 AS MAIO2, 6 AS JUNHO2, 7 AS JULHO2, 8 AS AGOSTO2, 9 AS SETEMBRO2, 10 AS OUTUBRO2, 11 AS NOVEMBRO2, 12 AS DEZEMBRO2))
